//
// Created by andrewnichols on 8/13/25.
//

#ifndef CANDIDATESCORESFEATUREMANAGER_H
#define CANDIDATESCORESFEATUREMANAGER_H

#include "AlgorithmsFFLib_Exports.h"

#include "Error.h"
#include "GlobalSettings.h"

using namespace Error;

class  ALGORITHMSFFLIB_EXPORTS CandidateScoresFeatureManager {

public:

    enum Features {
    	CosineSimSumTop8 = 0,
		CosineSimSumTop16,
		CosineSimSumGreaterThan80,
    	CosineSimSumMeanCorrelation,
    	CosineSimSumStDevCorrelation,
    	CosineSimSumTop8Tight1,
		CosineSimSumTop16Tight1,
		CosineSimSumGreaterThan80Tight1,
    	CosineSimSpectrumOverTime,
		CosineSimSpectrumOverTimeCubed,
		CosineSimSpectrumOverTimeStDev,

    	CosineSimToAnchorMS1MonoIsotope,
    	CosineSimToAnchorMS1C13,
    	CosineSimToAnchorMS1C132,
    	CosineSimToAnchorMS1PreMonoShadow,
    	CosineSimSumDiffMonoVsPreMonoShadow,
    	CosineSimSumDiffMonoVsPreMonoShadowAbs,

    	CosineSimToAnchor1,
		CosineSimToAnchor2,
		CosineSimToAnchor3,
		CosineSimToAnchor4,
		CosineSimToAnchor5,
		CosineSimToAnchor6,
		CosineSimToAnchor7,//40
		CosineSimToAnchor8,
		CosineSimToAnchor9,
		CosineSimToAnchor10,
		CosineSimToAnchor11,
		CosineSimToAnchor12,
		CosineSimToAnchor13,
		CosineSimToAnchor14,
		CosineSimToAnchor15,
		CosineSimToAnchorTight1_1,
		CosineSimToAnchorTight1_2,
		CosineSimToAnchorTight1_3,
		CosineSimToAnchorTight1_4,
		CosineSimToAnchorTight1_5,
		CosineSimToAnchorTight1_6,
		CosineSimToAnchorTight1_7,//40
		CosineSimToAnchorTight1_8,
		CosineSimToAnchorTight1_9,
		CosineSimToAnchorTight1_10,
		CosineSimToAnchorTight1_11,
		CosineSimToAnchorTight1_12,
		CosineSimToAnchorTight1_13,
		CosineSimToAnchorTight1_14,
		CosineSimToAnchorTight1_15,


	    // AllignedMaxIndexesCount,
	    // CosineSimMS1, //5
	    // CosineSimSpectrumCubed,
	    // KlDivSpectrumCubeRoot,
	    // CosineSimSum45,
	    // CosineSimSumTop,
	    // CosineSimSumBottom, //10
	    // TopBottomRatio,
	    // TopBottomRatioNorm,
	    // Charge,
	    // ScanTimeDelta,
	    // ScanTimeDeltaAbs, //15
	    // ScanTimePd,
	    // ScanTimePdAbs,
	    // ScanIonCount,
	    // MzNorm,
	    // Mass, //20
	    // KlDivSpectrum,
	    // CosineSimSpectrum,
	    // CosineSim45MS1,//20
	    // CosineSim100MS1PreMono,
	    // CosineSim100MS1Iso1,
	    // CosineSim100MS1Iso2,
	    // PeptideLengthNorm,
	    // ScanTimePredicted,
	    // TheoFragmentCount,
	    // TotalIntensityLog,
	    // PeakShapeRatio1,
	    // PeakShapeRatio2,//30
	    // PeakShapeRatio3,
	    // ShadowsCosineSimSum,
	    // IRTPredicted,
	    MzFoundMean1,
	    MzFoundMean2,
	    MzFoundMean3,
	    MzFoundMean4,
	    MzFoundMean5,
	    MzFoundMean6,
	    MzFoundMean7,
	    MzFoundMean8,
	    MzFoundMean9,
	    MzFoundMean10,
	    MzFoundMean11,
	    MzFoundMean12,
	    MzFoundMean13,
	    MzFoundMean14,
	    MzFoundMean15,
	    MzFoundMean16,
	    IntensityFoundMax1,
	    IntensityFoundMax2,
	    IntensityFoundMax3,
	    IntensityFoundMax4,
	    IntensityFoundMax5,
	    IntensityFoundMax6,
	    IntensityFoundMax7,
	    IntensityFoundMax8,
	    IntensityFoundMax9,
	    IntensityFoundMax10,
	    IntensityFoundMax11,
	    IntensityFoundMax12,
	    IntensityFoundMax13,
	    IntensityFoundMax14,
	    IntensityFoundMax15,
	    IntensityFoundMax16,
	    // IntensityFoundMaxNorm1,
	    // IntensityFoundMaxNorm2,
	    // IntensityFoundMaxNorm3,
	    // IntensityFoundMaxNorm4,
	    // IntensityFoundMaxNorm5,//110
	    // IntensityFoundMaxNorm6,
	    // IntensityFoundMaxNorm7,
	    // IntensityFoundMaxNorm8,
	    // IntensityFoundMaxNorm9,
	    // IntensityFoundMaxNorm10,
	    // IntensityFoundMaxNorm11,
	    // IntensityFoundMaxNorm12,
	    // AminoAcidCountA,
	    // AminoAcidCountC,
	    // AminoAcidCountD,
	    // AminoAcidCountE,
	    // AminoAcidCountF,
	    // AminoAcidCountG,
	    // AminoAcidCountH,
	    // AminoAcidCountI,
	    // AminoAcidCountK,//150
	    // AminoAcidCountL,
	    // AminoAcidCountM,
	    // AminoAcidCountN,
	    // AminoAcidCountP,
	    // AminoAcidCountQ,
	    // AminoAcidCountR,
	    // AminoAcidCountS,
	    // AminoAcidCountT,
	    // AminoAcidCountV,
	    // AminoAcidCountW,//160
	    // AminoAcidCountY,
	    // AminoAcidCountB,
	    // AminoAcidCountJ,
	    // AminoAcidCountO,
	    // AminoAcidCountU,
	    // AminoAcidCountX,
	    // AminoAcidCountZ,
	    // MzFoundStDev1,
	    // MzFoundStDev2,
	    // MzFoundStDev3,//170
	    // MzFoundStDev4,
	    // MzFoundStDev5,
	    // MzFoundStDev6,
	    // AltTargetKeyIdDiscScoreChargeOG_alt,
	    // AltTargetKeyIdDiscScoreCharge1_1,
	    // AltTargetKeyIdDiscScoreCharge1_2,
	    // AltTargetKeyIdDiscScoreCharge2_1,
	    // AltTargetKeyIdDiscScoreCharge2_2,
	    // AltTargetKeyIdDiscScoreCharge3_1,
	    // AltTargetKeyIdDiscScoreCharge3_2,
	    // AltTargetKeyIdDiscScoreCharge4_1,
	    // AltTargetKeyIdDiscScoreCharge4_2,
	    // AltTargetKeyIdTimeDeltaCharge1_1,
	    // AltTargetKeyIdTimeDeltaCharge2_1,
	    // AltTargetKeyIdTimeDeltaCharge3_1,
	    // AltTargetKeyIdTimeDeltaCharge4_1,
	    // Ms1MzMeanFound100,//220
	    // Ms1MzMeanFound45,
	    // Ms1MzMeanFoundPreMono,
	    // Ms1MzMeanFoundIso1,
	    // Ms1MzMeanFoundIso2,
	    // Ms1MzMeanFound100PPM,
	    // Ms1MzMeanFound45PPM,
	    // Ms1MzMeanFoundPreMonoPPM,
	    // Ms1MzMeanFoundIso1PPM,//230
	    // Ms1MzMeanFoundIso2PPM,
	    // Ms1MzStDevFound100,
	    // Ms1MzStDevFound45,
	    // Ms1MzStDevFoundPreMono,
	    // Ms1MzStDevFoundIso1,
	    // Ms1MzStDevFoundIso2,
	    // Ms1IntensityFound100,
	    // Ms1IntensityFoundApex100,
	    // Ms1IntensityFoundApex100IM,
	    // Ms1IntensityFound45,
	    // Ms1IntensityFoundPreMono,
	    // Ms1IntensityFoundIso1,
	    // Ms1IntensityFoundIso2,
	    //
	    // CosineSimSum100MS1,
	    // MS1Averagine,
	    // CosineSimSum100Window1p5X,//250
	    // CosineSimSum100Window2X,
	    // TotalIntensityPeakHeights,
	    // TotalIntensityRaw,
	    // TargetWindowLocation,
	    // TargetWindowLocationAbs,
	    // DiscriminantScore,
	    // AlignmentIndexMean,
	    // AlignmentIndexStDev,
	    // AlignmentCombinedScore,
	    // MatrixZeroPercentage,
	    // MzPPMMeanAbs,
	    // MzPPMMean,
	    // MzPPMStd,
	    // FoundB,
	    // FoundY,
	    // FoundPercent,
	    // DiscScore1stRunnerUp,
	    // DiscScore2ndRunnerUp,
	    // DiscScoresCount,
	    // DiscScoresMean,
	    // DiscScoresStDev,
	    // YIonSeriesMax,
	    // YIonSeriesCount,
	    // YIonSeriesMean,
	    // YIonSeriesStd,
	    // YIonSeriesTheoMax,
	    // YIonSeriesTheoCount,
	    // YIonSeriesTheoMean,
	    // YIonSeriesTheoStd,
	    // YIonSeriesMaxFoundToTheoFraction,
	    // YIonSeriesCountRatio,
	    // BIonSeriesMax,
	    // BIonSeriesCount,
	    // BIonSeriesMean,
	    // BIonSeriesStd,
	    // BIonSeriesTheoMax,
	    // BIonSeriesTheoCount,
	    // BIonSeriesTheoMean,
	    // BIonSeriesTheoStd,
	    // BIonSeriesMaxFoundToTheoFraction,
	    // BIonSeriesCountRatio,
	    // CosineSimFullTheo,
	    // IonsFoundFractionFull,
	    // CosineSimFullTheoXIonsFoundFractionFull,
	    //
	    // MzPeakLengthsNorm1,
	    // MzPeakLengthsNorm2,
	    // MzPeakLengthsNorm3,//120
	    // MzPeakLengthsNorm4,
	    // MzPeakLengthsNorm5,
	    // MzPeakLengthsNorm6,
	    // MzPeakLengthsNorm7,
	    // MzPeakLengthsNorm8,
	    // MzPeakLengthsNorm9,
	    // MzPeakLengthsNorm10,
	    // MzPeakLengthsNorm11,
	    // MzPeakLengthsNorm12,
	    // MzPeakLengthsMean,
	    // MzPeakLengthsStd,
	    // MonoPreMonoRatio,
	    // ApexDistanceFromAnchor1,
	    // ApexDistanceFromAnchor2,
	    // ApexDistanceFromAnchor3,
	    // ApexDistanceFromAnchor4,
	    // ApexDistanceFromAnchor5,
	    // ApexDistanceFromAnchor6,
	    // ApexDistanceFromAnchor7,
	    // ApexDistanceFromAnchor8,
	    // ApexDistanceFromAnchor9,
	    // ApexDistanceFromAnchor10,
	    // ApexDistanceFromAnchor11,
	    // ApexDistanceFromAnchor12,

	    FeaturesSize
	    };

	static QVector<Features> featuresCalibration();

};

using FTR = CandidateScoresFeatureManager::Features;

#endif //CANDIDATESCORESFEATUREMANAGER_H
