name: Build and Push Container

on:
  push:
    branches:
      - main

#TODO: configure builds for each architecture (x86_64 / aarch_64)
jobs:
  build-x86_64:
    # Require that this step run on a self-hosted runner
    # within the aws-master AWS account; this will ensure
    # it has the necessary access to ECR.
    runs-on: [self-hosted, aws-master, x86_64]

    env:
      CONTAINER_TAG: x86_64-build-${{ github.run_number }}

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build and tag container image
        uses: seerbio/action-build-container@1.1.0
        with:
          container: seer/pythia-dia-container
          repository: 718843040700.dkr.ecr.us-west-2.amazonaws.com
          test_script: ./test_container.sh

  build-aarch64:
    # Require that this step run on a self-hosted runner
    # within the aws-master AWS account; this will ensure
    # it has the necessary access to ECR.
    runs-on: [self-hosted, aws-master, aarch64]

    env:
      CONTAINER_TAG: aarch64-build-${{ github.run_number }}

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build and tag container image
        uses: seerbio/action-build-container@1.1.0
        with:
          container: seer/pythia-dia-container
          repository: 718843040700.dkr.ecr.us-west-2.amazonaws.com
          test_script: ./test_container.sh
