name: Tag Container

on:
  release:
    types: [created]

jobs:
  publish_x86_docker:
    runs-on: [self-hosted, aws-master, X64]
    steps:
      # Necessary to set up the token required to push the commit tag to GitHub
      - name: Check out code
        uses: actions/checkout@v6

      - name: Tag x86 container image
        uses: seerbio/action-tag-container@2.1.0
        with:
          container: seer/radiant-dia
          repository: 718843040700.dkr.ecr.us-west-2.amazonaws.com
          build_tag_prefix: x86_64-build-
          tag_suffix: -x86_64
          addl_tags: latest-x86_64

  publish_arm_docker:
    runs-on: [self-hosted, aws-master, ARM64]
    steps:
      # Necessary to set up the token required to push the commit tag to GitHub
      - name: Check out code
        uses: actions/checkout@v6

      - name: Tag ARM container image
        uses: seerbio/action-tag-container@2.1.0
        with:
          container: seer/radiant-dia
          repository: 718843040700.dkr.ecr.us-west-2.amazonaws.com
          build_tag_prefix: aarch64-build-
          tag_suffix: -aarch64
          addl_tags: latest-aarch64

  publish_docker_manifest:
    runs-on: [self-hosted, aws-master]
    needs: [publish_x86_docker, publish_arm_docker]
    steps:
      - name: Check out code
        uses: actions/checkout@v6
      - name: Publish Docker Manifest
        env:
          CONTAINER: seer/radiant-dia
          REPOSITORY: 718843040700.dkr.ecr.us-west-2.amazonaws.com
          ADDL_TAGS: latest
        run: ./deploy_docker_manifest.sh "${ADDL_TAGS}"

  publish_x86_deb:
    runs-on: [self-hosted, aws-master, X64]
    needs: publish_x86_docker
    steps:
      - name: Check out code
        uses: actions/checkout@v6
      - name: Upload x86 deb
        env:
          CONTAINER: seer/radiant-dia
          DEB_OUTPUT_DIR: ${{ runner.temp }}/deb-out
        run: ./deploy_deb.sh
      - name: Upload Release Artifacts
        if: ${{ github.event_name == 'release' }}
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ runner.temp }}/deb-out/*.deb
      - name: Upload Build Artifacts
        if: ${{ github.event_name != 'release' }}
        uses: actions/upload-artifact@v4
        with:
          name: radiantdia-deb-x86_64
          path: ${{ runner.temp }}/deb-out/*.deb


  publish_arm_deb:
    runs-on: [self-hosted, aws-master, ARM64]
    needs: publish_arm_docker
    steps:
      - name: Check out code
        uses: actions/checkout@v6
      - name: Upload ARM deb
        env:
          CONTAINER: seer/radiant-dia
          DEB_OUTPUT_DIR: ${{ runner.temp }}/deb-out
        run: ./deploy_deb.sh
      - name: Upload Release Artifacts
        if: ${{ github.event_name == 'release' }}
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ runner.temp }}/deb-out/*.deb
      - name: Upload Build Artifacts
        if: ${{ github.event_name != 'release' }}
        uses: actions/upload-artifact@v4
        with:
          name: radiantdia-deb-arm64
          path: ${{ runner.temp }}/deb-out/*.deb
